/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructureassignment2;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static datastructureassignment2.Frame_addSoftware.software_list;
import static datastructureassignment2.Frame_addSoftware.softList;
import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author Admin
 */
public class Frame_SearchSoftware extends javax.swing.JFrame {

    /**
     * Creates new form Frame_SearchSoftware
     */
    public Frame_SearchSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        showbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        softwaretxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        computertbl = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setText("Lab&Computer Searching Engine");

        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Software");

        computertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Software", "Block", "Floor", "Lab ID", "Computer ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        computertbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(computertbl);

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setText("Search Software");

        jButton1.setText("Check Duplicate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(softwaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(313, 313, 313))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(softwaretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed

        long startTime = System.nanoTime();

        String data = softwaretxt.getText();
        String str = software_list.search_software(data).toString();
        long stopTime = System.nanoTime();
        long totalTime = stopTime - startTime;
        String count = software_list.count(data);

        int flagg = 0;

        try {

            for (int a = 0; a < Integer.parseInt(count); a++) {
                String[] labbs = str.split(",");
                String softwares = labbs[0 + a * 5];
                String block = labbs[1 + a * 5];
                String levell = labbs[2 + a * 5];
                String labid = labbs[3 + a * 5];
                String comid = labbs[4 + a * 5];
                if (data.matches(softwares)) {
                    flagg = 1;
                    break;
                } else if (specialChar(data)) { //special char
                    flagg = 3;
                    break;
//                } else if (isEmpty(spec)) { //empty
//                    flagg = 4;
//                    break;
                } else {
                    flagg = 2;
                }

            }

            switch (flagg) {
                case 1:
                    showTable(data);
                    JOptionPane.showMessageDialog(null, totalTime + " nano second", "Run time", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 2:
                    boolean empty = isEmpty(softwaretxt.getText());
                    if (empty == true) { //false
                        JOptionPane.showMessageDialog(null, "Please key in the Specification", "Please try again", JOptionPane.ERROR_MESSAGE);
                        rst();
                    } else { //blank
                        JOptionPane.showMessageDialog(null, "The Specification does not exist", "Please try again", JOptionPane.ERROR_MESSAGE);
                        rst();
                    }
                    break;
                case 3:
                    JOptionPane.showMessageDialog(null, "Search cannot contain special characters", "Please try again", JOptionPane.ERROR_MESSAGE);
                    rst();
                    break;
                case 4:
                    JOptionPane.showMessageDialog(null, "Please key in the Specification", "Please try again", JOptionPane.ERROR_MESSAGE);
                    rst();
                default:
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_showbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        try {
            BufferedReader lgnuser = new BufferedReader(new FileReader("loginn.txt"));
            String strLine = null, tmp;
            while ((tmp = lgnuser.readLine()) != null) {
                strLine = tmp;
            }
            String utype = strLine;

            if (utype.equals("Student")) {
                Frame_Student fs = new Frame_Student();
                fs.setVisible(true);
                this.setVisible(false);
            } else {
                Frame_addSoftware fc = new Frame_addSoftware();
                fc.setVisible(true);
                this.setVisible(false);
            }
            lgnuser.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_backbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel table = new DefaultTableModel(new String[]{"Software", "Block", "Floor", "Lab ID", "Computer ID"}, 0);
        computertbl.setModel(table);

        Check<software> x = (Check<software>) softList.checkDuplicate();
        String results = "There is no Duplicate";
//        System.out.println(x.size);
        for (int y = 0; y < x.size; y++) {
            results = x.get(y).toString();
            System.out.println(results);
            if (results != null) {
                String[] labbs = results.split(",");
                String softwares = labbs[0];
                String block = labbs[1];
                String levell = labbs[2];
                String labid = labbs[3];
                String comid = labbs[4];

                for (int i = 0; i < results.length(); i++) {
                    Object[] row = new Object[5];
                    row[0] = softwares;
                    row[1] = block;
                    row[2] = levell;
                    row[3] = labid;
                    row[4] = comid;
                    table.addRow(row);
                    break;
                }
            }

//            System.out.println(x.get(y).toString());
            //labbbb = x.get(y).getLabb().getLabID().toString();
        }
        //JOptionPane.showMessageDialog(null, results, "Duplicate", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_SearchSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_SearchSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_SearchSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_SearchSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_SearchSoftware().setVisible(true);
            }
        });
    }

    public void showTable(String data) {
        String str = software_list.search_software(data);
        String count = software_list.count(data);

        DefaultTableModel table = new DefaultTableModel(new String[]{"Software", "Block", "Floor", "Lab ID", "Computer ID"}, 0);
        computertbl.setModel(table);

        try {
            for (int a = 0; a < Integer.parseInt(count); a++) {
                String[] labbs = str.split(",");
                String softwares = labbs[0 + a * 5];
                String block = labbs[1 + a * 5];
                String levell = labbs[2 + a * 5];
                String labid = labbs[3 + a * 5];
                String comid = labbs[4 + a * 5];
                if (data.matches(softwares)) {
                    for (int i = 0; i < str.length(); i++) {
                        Object[] row = new Object[5];
                        row[0] = softwares;
                        row[1] = block;
                        row[2] = levell;
                        row[3] = labid;
                        row[4] = comid;
                        table.addRow(row);
                        break;
                    }
                }

            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        JOptionPane.showMessageDialog(null, computertbl.getRowCount() + " results found!");
    }

    public void rst() {
        DefaultTableModel dm = (DefaultTableModel) computertbl.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }
    }

    public static boolean specialChar(String input) {
        boolean special;
        Pattern regex = Pattern.compile("[$&+,:;=\\\\?@#|/'<>.^*()%!-]");
        if (regex.matcher(input).find()) {
            special = true;
        } else {
            return false;
        }
        return special;
    }

    public boolean isEmpty(String input) {
        int count;
        count = input.length();
        boolean empty;
        if (count == 0) {
            empty = true;
        } else {
            return false;
        }
        return empty;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTable computertbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showbtn;
    private javax.swing.JTextField softwaretxt;
    // End of variables declaration//GEN-END:variables
}
