/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructureassignment2;

import javax.swing.JOptionPane;
import static datastructureassignment2.DataStructureAssignment20.bst;
import static datastructureassignment2.DataStructureAssignment20.lll;
import static datastructureassignment2.DataStructureAssignment20.searchh;
import static datastructureassignment2.DataStructureAssignment20.compp;
//import static datastructureassignment2.DataStructureAssignment20.comppList;
import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author DELL
 */
public class Frame_Lab extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Lab
     */
    private String utype;

    public Frame_Lab() {
        initComponents();
//        bst.add(new Lab("B101", "B", 1, "Network", 30));
//        bst.add(new Lab("B104", "B", 1, "Network", 30));
//        bst.add(new Lab("B102", "B", 1, "Network", 30));
//        bst.add(new Lab("B103", "B", 1, "Web Application", 30));
//        bst.add(new Lab("D301", "D", 3, "Data Structure", 30));
//        bst.displayy();
        addblocktxt.setEnabled(false);
        addleveltxt.setEnabled(false);
        addspectxt.setEnabled(false);
        addcapacitytxt.setEnabled(false);
        addbtn.setEnabled(false);
        deletebtn.setEnabled(false);

        deviceIDtxt.setEnabled(false);
        processortxt.setEnabled(false);
        ramtxt.setEnabled(false);
        ostxt.setEnabled(false);
        jButton1.setEnabled(false);

        try {
            BufferedReader lgnuser = new BufferedReader(new FileReader("loginn.txt"));
            String strLine = null, tmp;
            while ((tmp = lgnuser.readLine()) != null) {
                strLine = tmp;
            }
            utype = strLine;         

            if (utype.equals("Student")) {
                jTabbedPane2.removeAll();
                jTabbedPane2.add("Lab", jTabbedPane1);
                jTabbedPane2.add("Computer", jTabbedPane3);

                jTabbedPane1.removeAll();
                jTabbedPane1.addTab("Search Lab", jPanel2);

                jTabbedPane3.removeAll();
                jTabbedPane3.addTab("Search Computer", jPanel5);

            }
            lgnuser.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labidtxt = new javax.swing.JTextField();
        searchcomptxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        levelllllllllllll = new javax.swing.JLabel();
        leveltxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spectxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        capacitytxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        blocktxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        addcapacitytxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addblocktxt = new javax.swing.JTextField();
        labidtxt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        levelllllllllllll1 = new javax.swing.JLabel();
        addleveltxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addspectxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deletecapacitytxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deleteblocktxt = new javax.swing.JTextField();
        deletelabidtxt = new javax.swing.JTextField();
        deletesearchtxt = new javax.swing.JTextField();
        deleteSearchBtn = new javax.swing.JButton();
        levelllllllllllll2 = new javax.swing.JLabel();
        deleteleveltxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        deletespectxt = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        compsearchbtn1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ramtxt2 = new javax.swing.JTextField();
        deviceIDtxt2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        levelllllllllllll5 = new javax.swing.JLabel();
        ostxt2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        labtxt2 = new javax.swing.JTextField();
        processortxt2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ramtxt1 = new javax.swing.JTextField();
        deviceIDtxt1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        levelllllllllllll4 = new javax.swing.JLabel();
        ostxt1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        labtxt1 = new javax.swing.JTextField();
        processortxt1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        compsearchtxt = new javax.swing.JTextField();
        compsearchbtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        deviceIDtxt = new javax.swing.JTextField();
        levelllllllllllll3 = new javax.swing.JLabel();
        processortxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ramtxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ostxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer & Lab Search Engine");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setText("Computer & Lab Search Engine");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Search for computer lab");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Lab ID");

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        levelllllllllllll.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll.setText("Level");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Specification");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Capacity");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Block");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(capacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(levelllllllllllll)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(blocktxt)
                            .addComponent(spectxt)
                            .addComponent(leveltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(searchcomptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchbtn))
                            .addComponent(labidtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchcomptxt)
                    .addComponent(searchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(blocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll)
                    .addComponent(leveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(capacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Search Lab", jPanel2);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Capacity");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Block");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Lab ID");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        levelllllllllllll1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll1.setText("Level");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Specification");

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addcapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(levelllllllllllll1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addblocktxt)
                            .addComponent(addspectxt)
                            .addComponent(addleveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(132, 132, Short.MAX_VALUE)
                        .addComponent(labidtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labidtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addblocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll1)
                    .addComponent(addleveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(addspectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addcapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Lab", jPanel1);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Capacity");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Search for computer lab");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Block");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Lab ID");

        deleteSearchBtn.setText("Search");
        deleteSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSearchBtnActionPerformed(evt);
            }
        });

        levelllllllllllll2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll2.setText("Level");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Specification");

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletecapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(levelllllllllllll2)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteblocktxt)
                            .addComponent(deletespectxt)
                            .addComponent(deleteleveltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(deletesearchtxt)
                                .addGap(18, 18, 18)
                                .addComponent(deleteSearchBtn))
                            .addComponent(deletelabidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletesearchtxt)
                    .addComponent(deleteSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(deletelabidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(deleteblocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll2)
                    .addComponent(deleteleveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(deletespectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(deletecapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletebtn)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Delete Lab", jPanel3);

        jTabbedPane2.addTab("Lab", jTabbedPane1);

        compsearchbtn1.setText("Search");
        compsearchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compsearchbtn1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setText("RAM");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setText("Device ID");

        ramtxt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        deviceIDtxt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setText("Operating System(OS)");

        levelllllllllllll5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll5.setText("Processor");

        ostxt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setText("Computer Lab");

        labtxt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        processortxt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelllllllllllll5)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(deviceIDtxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labtxt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(ostxt2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ramtxt2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processortxt2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator5)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(0, 395, Short.MAX_VALUE)
                            .addComponent(compsearchbtn1)))
                    .addGap(39, 39, 39)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(deviceIDtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll5)
                    .addComponent(processortxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ramtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(ostxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(labtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(compsearchbtn1)
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(381, 381, 381)))
        );

        jTabbedPane3.addTab("Search computer", jPanel5);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setText("RAM");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Device ID");

        ramtxt1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        deviceIDtxt1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setText("Operating System(OS)");

        levelllllllllllll4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll4.setText("Processor");

        ostxt1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setText("Computer Lab");

        labtxt1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        processortxt1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(levelllllllllllll4)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labtxt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ostxt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processortxt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(deviceIDtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(ramtxt1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jSeparator4))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(deviceIDtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll4)
                    .addComponent(processortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ramtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(labtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Remove computer", jPanel7);

        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Computer Lab");

        compsearchbtn.setText("Search");
        compsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compsearchbtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Device ID");

        deviceIDtxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        levelllllllllllll3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        levelllllllllllll3.setText("Processor");

        processortxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("RAM");

        ramtxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Operating System(OS)");

        ostxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(compsearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(compsearchbtn))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(levelllllllllllll3)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ramtxt)
                            .addComponent(processortxt)
                            .addComponent(ostxt)
                            .addComponent(deviceIDtxt))))
                .addGap(39, 39, 39))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compsearchtxt)
                    .addComponent(compsearchbtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(deviceIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelllllllllllll3)
                    .addComponent(processortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ramtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(86, 86, 86)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(414, 414, 414))
        );

        jTabbedPane3.addTab("Add new computer", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Computer", jPanel4);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        long startTime = System.nanoTime();

        String data = searchcomptxt.getText();
        String result = bst.search(data);

        if (result != "Lab not found") {
            long stopTime = System.nanoTime();
            long totalTime = stopTime - startTime;

            labidtxt.setText(lll.getLabID());
            labidtxt.setEnabled(false);

            blocktxt.setText(lll.getBlock());
            blocktxt.setEnabled(false);

            String levelll = Integer.toString(lll.getLevel());
            leveltxt.setText(levelll);
            leveltxt.setEnabled(false);

            spectxt.setText(lll.getLabSpecification());
            spectxt.setEnabled(false);

            String capacity = Integer.toString(lll.getLabCapacity());
            capacitytxt.setText(capacity);
            capacitytxt.setEnabled(false);

            JOptionPane.showMessageDialog(null, totalTime + " nano second", "Run time", JOptionPane.INFORMATION_MESSAGE);

        } else {
            searchcomptxt.setText(null);
            labidtxt.setText(null);
            blocktxt.setText(null);
            leveltxt.setText(null);
            spectxt.setText(null);
            capacitytxt.setText(null);
            JOptionPane.showMessageDialog(null, data + ", " + result, "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long startTime = System.nanoTime();
        String labID = labidtxt1.getText();
//        String block = addblocktxt.getText();
//        int level = Integer.parseInt(addleveltxt.getText());
//        String spec = addspectxt.getText();
//        int capacity = Integer.parseInt(addcapacitytxt.getText());
//        System.out.println(bst.containz(labID));
        boolean result = bst.containz(labID);
        long stopTime = System.nanoTime();
        long totalTime = stopTime - startTime;

        if (result == true) {
            JOptionPane.showMessageDialog(null, totalTime + " nano second, the lab already exist!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, totalTime + " nano second\nThere is no " + labID + " yet.", "Run time", JOptionPane.INFORMATION_MESSAGE);
            addblocktxt.setEnabled(true);
            addleveltxt.setEnabled(true);
            addspectxt.setEnabled(true);
            addcapacitytxt.setEnabled(true);
            addbtn.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String labID = labidtxt1.getText();
        String block = addblocktxt.getText();
        int level = Integer.parseInt(addleveltxt.getText());
        String spec = addspectxt.getText();
        int capacity = Integer.parseInt(addcapacitytxt.getText());

        bst.add(new Lab(labID, block, level, spec, capacity));

        String result = bst.search(labID);
        JOptionPane.showMessageDialog(null, result + "\nThe result is added to the record!", "Add new Lab", JOptionPane.INFORMATION_MESSAGE);

        labidtxt1.setText(null);
        addblocktxt.setText(null);
        addleveltxt.setText(null);
        addspectxt.setText(null);
        addcapacitytxt.setText(null);
    }//GEN-LAST:event_addbtnActionPerformed

    private void deleteSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSearchBtnActionPerformed
        long startTime = System.nanoTime();

        String data = deletesearchtxt.getText();
        String result = bst.search(data);

        if (result != "Lab not found") {
            long stopTime = System.nanoTime();
            long totalTime = stopTime - startTime;

            deletelabidtxt.setText(lll.getLabID());
            deletelabidtxt.setEnabled(false);

            deleteblocktxt.setText(lll.getBlock());
            deleteblocktxt.setEnabled(false);

            String levelll = Integer.toString(lll.getLevel());
            deleteleveltxt.setText(levelll);
            deleteleveltxt.setEnabled(false);

            deletespectxt.setText(lll.getLabSpecification());
            deletespectxt.setEnabled(false);

            String capacity = Integer.toString(lll.getLabCapacity());
            deletecapacitytxt.setText(capacity);
            deletecapacitytxt.setEnabled(false);

            JOptionPane.showMessageDialog(null, totalTime + " nano second", "Run time", JOptionPane.INFORMATION_MESSAGE);
            deletebtn.setEnabled(true);
        } else {
            deletesearchtxt.setText(null);
            deletelabidtxt.setText(null);
            deleteblocktxt.setText(null);
            deleteleveltxt.setText(null);
            deletespectxt.setText(null);
            deletecapacitytxt.setText(null);
            JOptionPane.showMessageDialog(null, data + ", " + result, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteSearchBtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String data = deletesearchtxt.getText();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + data, "Delete", JOptionPane.WARNING_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            bst.remove(data);
            deletesearchtxt.setText(null);
            deletelabidtxt.setText(null);
            deleteblocktxt.setText(null);
            deleteleveltxt.setText(null);
            deletespectxt.setText(null);
            deletecapacitytxt.setText(null);
        } else {

        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void compsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compsearchbtnActionPerformed
        long startTime = System.nanoTime();
        String labID = compsearchtxt.getText();
        boolean result = bst.containz(labID);
        long stopTime = System.nanoTime();
        long totalTime = stopTime - startTime;

        if (result == false) {
            JOptionPane.showMessageDialog(null, totalTime + " nano second\nThere is no " + labID + ".", "Run time", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, totalTime + " nano second, the lab exist!", "Run time", JOptionPane.INFORMATION_MESSAGE);
            deviceIDtxt.setEnabled(true);
            processortxt.setEnabled(true);
            ramtxt.setEnabled(true);
            ostxt.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_compsearchbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String labbb = compsearchtxt.getText();
        String deviceID = deviceIDtxt.getText();
        String processorrr = processortxt.getText();
        String ramm = ramtxt.getText();
        String oss = ostxt.getText();

        bst.search(labbb);
        //System.out.println(lll.getLabID() + lll.getBlock() + lll.getLevel() + lll.getLabSpecification() + lll.getLabCapacity());
        Lab test = new Lab(lll.getLabID(), lll.getBlock(), lll.getLevel(), lll.getLabSpecification(), lll.getLabCapacity());

        searchh.add(new Computer(deviceID, processorrr, ramm, oss,test));
        //comppList.add(new Computer(deviceID, processorrr, ramm, oss,test));
        String rrresult = searchh.searchz(deviceID);
        JOptionPane.showMessageDialog(null, rrresult + "\nThe result is added to the record!", "Add new Computer", JOptionPane.INFORMATION_MESSAGE);

        compsearchtxt.setText(null);
        deviceIDtxt.setText(null);
        processortxt.setText(null);
        ramtxt.setText(null);
        ostxt.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void compsearchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compsearchbtn1ActionPerformed
        long startTime = System.nanoTime();

        String data = deviceIDtxt2.getText();
        String result = searchh.searchz(data);

        if (result != "Computer not found") {
            long stopTime = System.nanoTime();
            long totalTime = stopTime - startTime;

            processortxt2.setText(compp.getProcessor());
            processortxt2.setEnabled(false);

            ramtxt2.setText(compp.getRam());
            ramtxt2.setEnabled(false);

            ostxt2.setText(compp.getOs());
            ostxt2.setEnabled(false);

            labtxt2.setText(compp.getLabb().getLabID());
            labtxt2.setEnabled(false);

            JOptionPane.showMessageDialog(null, totalTime + " nano second", "Run time", JOptionPane.INFORMATION_MESSAGE);

        } else {
            deviceIDtxt2.setText(null);
            processortxt2.setText(null);
            ramtxt2.setText(null);
            ostxt2.setText(null);
            labtxt2.setText(null);
            JOptionPane.showMessageDialog(null, data + ", " + result, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_compsearchbtn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        long startTime = System.nanoTime();
        String compID = deviceIDtxt1.getText();
        boolean result = searchh.containz(compID);
        long stopTime = System.nanoTime();
        long totalTime = stopTime - startTime;

        if (result == false) {
            JOptionPane.showMessageDialog(null, totalTime + " nano second\nThere is no " + compID + ".", "Run time", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, totalTime + " nano second, the Computer exist!", "Run time", JOptionPane.INFORMATION_MESSAGE);
            processortxt1.setText(compp.getProcessor());
            processortxt1.setEnabled(false);

            ramtxt1.setText(compp.getRam());
            ramtxt1.setEnabled(false);

            ostxt1.setText(compp.getOs());
            ostxt1.setEnabled(false);

            labtxt1.setText(compp.getLabb().getLabID());
            labtxt1.setEnabled(false);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String data = deviceIDtxt1.getText();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + data, "Delete", JOptionPane.WARNING_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            searchh.remove(data);
            deviceIDtxt1.setText(null);
            processortxt1.setText(null);
            ramtxt1.setText(null);
            ostxt1.setText(null);
            labtxt1.setText(null);
        } else {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            BufferedReader lgnuser = new BufferedReader(new FileReader("loginn.txt"));
            String strLine = null, tmp;
            while ((tmp = lgnuser.readLine()) != null) {
                strLine = tmp;
            }
            utype = strLine;         

            if (utype.equals("Student")) {
                Frame_Student fs = new Frame_Student();
                fs.setVisible(true);
                this.setVisible(false);
            } else {
                Frame_Admin fa = new Frame_Admin();
                fa.setVisible(true);
                this.setVisible(false);
            }
            lgnuser.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Lab().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addblocktxt;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField addcapacitytxt;
    private javax.swing.JTextField addleveltxt;
    private javax.swing.JTextField addspectxt;
    private javax.swing.JTextField blocktxt;
    private javax.swing.JTextField capacitytxt;
    private javax.swing.JButton compsearchbtn;
    private javax.swing.JButton compsearchbtn1;
    private javax.swing.JTextField compsearchtxt;
    private javax.swing.JButton deleteSearchBtn;
    private javax.swing.JTextField deleteblocktxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField deletecapacitytxt;
    private javax.swing.JTextField deletelabidtxt;
    private javax.swing.JTextField deleteleveltxt;
    private javax.swing.JTextField deletesearchtxt;
    private javax.swing.JTextField deletespectxt;
    private javax.swing.JTextField deviceIDtxt;
    private javax.swing.JTextField deviceIDtxt1;
    private javax.swing.JTextField deviceIDtxt2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField labidtxt;
    private javax.swing.JTextField labidtxt1;
    private javax.swing.JTextField labtxt1;
    private javax.swing.JTextField labtxt2;
    private javax.swing.JLabel levelllllllllllll;
    private javax.swing.JLabel levelllllllllllll1;
    private javax.swing.JLabel levelllllllllllll2;
    private javax.swing.JLabel levelllllllllllll3;
    private javax.swing.JLabel levelllllllllllll4;
    private javax.swing.JLabel levelllllllllllll5;
    private javax.swing.JTextField leveltxt;
    private javax.swing.JTextField ostxt;
    private javax.swing.JTextField ostxt1;
    private javax.swing.JTextField ostxt2;
    private javax.swing.JTextField processortxt;
    private javax.swing.JTextField processortxt1;
    private javax.swing.JTextField processortxt2;
    private javax.swing.JTextField ramtxt;
    private javax.swing.JTextField ramtxt1;
    private javax.swing.JTextField ramtxt2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchcomptxt;
    private javax.swing.JTextField spectxt;
    // End of variables declaration//GEN-END:variables
}
